package com.gubee.stockreconciliation.domain.model;

public enum ProcessingStatus {
    APPLIED,
    AUDITED,
    IGNORED_DUPLICATE_EVENT,
    IGNORED_DUPLICATE_ORDER,
    REJECTED_DUPLICATE_EVENT_ID,
    REJECTED_INSUFFICIENT_STOCK,
    REJECTED_ORDER_NOT_FOUND,
    REJECTED_ORDER_ALREADY_CANCELLED,
    REJECTED_INVALID_CANCEL_QUANTITY
}
